var beings = [{
    "title": "Being#001",
    "Being": "#001",
    "Date": "7 December",
    "Location": "Shanghai, China",
    "PhysicalAppearance": "Masculine. Silver hair and skin",
    "Height": "1.89m",
    "Wingspan": "2.55m",
    "AdditionalInfo": "Fall caught on camera by Roberto Bartolucci, an Italian tourist. The video quickly became the most-watched in internet history.",
    "lat": 31.181141,
    "lng": 121.493981
  },
  {
    "title": "Being#002",
    "Being": "#002",
    "Date": "10 December",
    "Location": "Mulanje, Malawi",
    "PhysicalAppearance": "Feminine. Metallic red skin, almost black hair",
    "Height": "1.78m",
    "Wingspan": "2.42m",
    "AdditionalInfo": "Landed in the hills just outside the town of Mulanje. Body retrieved by a young couple, who sold it to an American research centre for an undisclosed sum.",
    "lat": -16.001607,
    "lng": 35.526828
  },
  {
    "title": "Being#003",
    "Being": "#003",
    "Date": "12 December",
    "Location": "Off the coast of San Juan del Sur, Nicaragua",
    "PhysicalAppearance": "Feminine. Silver-coloured skin and hair",
    "Height": "1.52m",
    "Wingspan": "2.65m",
    "AdditionalInfo": "Fell during a storm. Many of the feathers were torn from the Being’s wings and washed away – some were found along the coast of Costa Rica as much as five months later.",
    "lat": 11.252655,
    "lng": -85.882623
  },
  {
    "title": "Being#004",
    "Being": "#004",
    "Date": "20 December",
    "Location": "Hassi Messaoud, Algeria",
    "PhysicalAppearance": "Masculine. Golden skin, copper hair",
    "Height": "1.59m",
    "Wingspan": "2.38m",
    "AdditionalInfo": "Fall spotted by a man named Rachid Djaout, who was travelling along the N3 road. The body was recovered and sold to a South Korean research centre for a rumoured 227 billion won (approx. £150m).",
    "lat": 29.933138,
    "lng": 7.027990
  },
  {
    "title": "Being#005",
    "Being": "#005",
    "Date": "21 December",
    "Location": "Washed up on the island of Siberut, Indonesia",
    "PhysicalAppearance": "Feminine. Very pale bronze skin and hair",
    "Height": "1.90m",
    "Wingspan": "2.88m",
    "AdditionalInfo": "The majority of the Being’s feathers were removed by a group of British and Danish tourists, who were later charged with vandalism of Indonesian public property and fined. The feathers were confiscated and are now on display in a museum in Jakarta.",
    "lat": -1.778140,
    "lng": 99.261392
  },
  {
    "title": "Being#006",
    "Being": "#006",
    "Date": "22 December",
    "Location": "Norwegian Sea – taken to Norway",
    "PhysicalAppearance": "Feminine. Dark metallic red skin, black hair",
    "Height": "1.37m",
    "Wingspan": "2.4m",
    "AdditionalInfo": "Body retrieved by a Norwegian fishing boat. One of the fisherman onboard was named Alvin Engel, German for ‘angel’.",
    "lat": 66.529616,
    "lng": 2.693629
  },
  {
    "title": "Being#007",
    "Being": "#007",
    "Date": "31 December",
    "Location": "Perm, Russia",
    "PhysicalAppearance": "Feminine. Metallic brown skin, silver hair",
    "Height": "1.67m",
    "Wingspan": "2.76m",
    "AdditionalInfo": "Fell in Yegoshika Cemetery, destroying several graves. The Being’s feathers were mostly removed by citizens visiting the cemetery – reports claimed the feathers sold for up to a million rubles (approx. £13,000) online.",
    "lat": 58.012248,
    "lng": 56.270432
  },
  {
    "title": "Being#008",
    "Being": "#008",
    "Date": "1 January",
    "Location": "Edinburgh, Scotland",
    "PhysicalAppearance": "Masculine. Dark copper skin, black hair",
    "Height": "2m",
    "Wingspan": "2.89m",
    "AdditionalInfo": "Fell through the roof of St Giles’ Cathedral. Tours of the site are now available (£12/9 conc.)",
    "lat": 55.949482,
    "lng": -3.191297
  },
  {
    "title": "Being#009",
    "Being": "#009",
    "Date": "5 January",
    "Location": "Gulf of Guinea – taken to Togo",
    "PhysicalAppearance": "Feminine. Silver skin, white hair",
    "Height": "1.88m",
    "Wingspan": "2.66m",
    "AdditionalInfo": "Fall happened too far from shore for anyone to witness it, but a 6-year-old girl named Adjo Talakaena saw it happen in a dream. Her father took her out on his boat and Adio was able to recover the body. She was later invited onto Ellen to discuss the discovery.",
    "lat": 6.027618,
    "lng": 1.536364
  },
  {
    "title": "Being#010",
    "Being": "#010",
    "Date": "6 January",
    "Location": "Loma Mountains, Sierra Leone",
    "PhysicalAppearance": "Masculine. Golden skin and hair",
    "Height": "1.62m",
    "Wingspan": "2.32m",
    "AdditionalInfo": "Body discovered by Red Colobus monkeys, who had removed many of the feathers by the time it was retrieved. The Being was unusual in that its blood was a dark metallic red, unlike the usual gold.",
    "lat": 9.189875,
    "lng": -11.116643
  },
  {
    "title": "Being#011",
    "Being": "#011",
    "Date": "10 January",
    "Location": "Washed up in Paka, Malaysia",
    "PhysicalAppearance": "Masculine. Dark copper skin, black hair.",
    "Height": "1.68m",
    "Wingspan": "2.33m",
    "AdditionalInfo": "Body estimated to have fallen 2-3 days before being recovered by locals. It is currently on display in a museum in the capital city of Kuala Lumpur, along with Being #030.",
    "lat": 4.641675,
    "lng": 103.437912
  },
  {
    "title": "Being#012",
    "Being": "#012",
    "Date": "13 January",
    "Location": "Ile-Alatau National Park, Kazakhstan",
    "PhysicalAppearance": "Masculine. Very pale golden skin, silver hair.",
    "Height": "1.74m",
    "Wingspan": "2.65m",
    "AdditionalInfo": "Body spotted by hillwalkers and sold to Kazakh billionaire Timur Talgatov for an undisclosed sum. There are unconfirmed reports that he had necklaces made from the Being’s feathers for his wife and daughter.",
    "lat": 43.079320,
    "lng": 77.055020
  },
  {
    "title": "Being#013",
    "Being": "#013",
    "Date": "13 January",
    "Location": "North Queensferry, Scotland",
    "PhysicalAppearance": "Feminine. Silver skin, black hair.",
    "Height": "1.54m",
    "Wingspan": "2.42m",
    "AdditionalInfo": "Spotted at 2.15am by a man on the Forth Road Bridge. According to a subsequent interview in the Scotsman, he had been about to jump but reconsidered after seeing the Being fall.",
    "lat": 56.009119,
    "lng": -3.403327
  },
  {
    "title": "Being#014",
    "Being": "#014",
    "Date": "14 January",
    "Location": "Off the coast of Mazatlán, Mexico",
    "PhysicalAppearance": "Feminine. Metallic orange skin, golden hair.",
    "Height": "1.74m",
    "Wingspan": "2.97m",
    "AdditionalInfo": "Fall witnessed by an elderly couple, Diego Ramírez and Ana María Fonseca. Deeply religious, they chose to give the Being a dignified burial rather than selling its body. The site of the grave is unknown.",
    "lat": 23.216126,
    "lng": -106.428803
  },
  {
    "title": "Being#015",
    "Being": "#015",
    "Date": "19 January",
    "Location": "Rincón de Valentín, Uruguay",
    "PhysicalAppearance": "Masculine. Metallic dark red skin, white hair.",
    "Height": "1.84m",
    "Wingspan": "2.67m",
    "AdditionalInfo": "Body found by a family driving past, who sold it to an American research centre for a reported $350 million, splitting the payment between the residents of their town.",
    "lat": -31.274945,
    "lng": -57.206504
  },
  {
    "title": "Being#016",
    "Being": "#016",
    "Date": "3 February",
    "Location": "N’Goussa, Algeria",
    "PhysicalAppearance": "Feminine. Golden skin, silver hair.",
    "Height": "1.95m",
    "Wingspan": "2.87m",
    "AdditionalInfo": "Fell just after the first call to prayer and was witnessed by several people on their way to Mosque – amongst them was Rachid Djaout, who also saw Being #004 land on 20 December.",
    "lat": 32.141570,
    "lng": 5.309352
  },
  {
    "title": "Being#017",
    "Being": "#017",
    "Date": "4 February",
    "Location": "Off the coast of Mozambique",
    "PhysicalAppearance": "Masculine. Silver skin, dark grey hair.",
    "Height": "1.45m",
    "Wingspan": "2.57m",
    "AdditionalInfo": "Fall spotted by passengers on a cruise ship, one of whom nearly drowned when he attempted to swim to retrieve the body. Sold to an American university for an undisclosed amount.",
    "lat": -16.056533,
    "lng": 40.639867
  },
  {
    "title": "Being#018",
    "Being": "#018",
    "Date": "6 February",
    "Location": "Red Mountain, Colorado, USA",
    "PhysicalAppearance": "Masculine. Silver skin, silver-white hair.",
    "Height": "1.62m",
    "Wingspan": "2.70m",
    "AdditionalInfo": "Fall witnessed by a group of UFO watchers at approximately 3.15am. The body is on display at the site, now a tourist attraction with a dedicated gift shop and restaurant (entrance $55).",
    "lat": 37.901389,
    "lng": -107.693016
  },
  {
    "title": "Being#019",
    "Being": "#019",
    "Date": "8 February",
    "Location": "River Solimões, Brazil",
    "PhysicalAppearance": "Feminine. Metallic brown skin, golden hair.",
    "Height": "1.42m",
    "Wingspan": "2.01m",
    "AdditionalInfo": "Fall estimated to have taken place further north, with the body being washed downstream. It was sold to an anonymous Chinese buyer, though some of its feathers are on display in a museum in Río de Janeiro.",
    "lat": -3.317422,
    "lng": -64.560600
  },
  {
    "title": "Being#020",
    "Being": "#020",
    "Date": "8 February",
    "Location": "Red Sea – taken to Al Qunfudhah, Saudi Arabia ",
    "PhysicalAppearance": "Feminine. Copper skin, no hair.",
    "Height": "1.6m",
    "Wingspan": "2.56m",
    "AdditionalInfo": "Body retrieved by the Royal Saudi Navy. The Being had lost most of its wings mid-flight and was reported as selling for a relatively low price to a research centre in the United Arab Emirates.",
    "lat": 19.118371,
    "lng": 41.045056
  }
];
